[workspace]
members = ["classifier", "log-processor", "queue-processor", "blocklist-server"]
resolver = "2"

[workspace.dependencies]
base64ct = "1.6"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "json", "chrono", "migrate"] }
strum = { version = "0.26", features = ["derive"] }

[workspace.package]
edition = "2024"

[package]
name = "dns-smart-block"
version = "0.1.0"
edition = "2024"
publish = false

[dev-dependencies]
cargo-husky = { version = "1", features = ["user-hooks"] }